server:
  port: 9000
  servlet:
    context-path: /oauth
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth
    username: "oauth"
    password: "00227"
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 0
      port: 6379
      password:
      host: 127.0.0.1


