package top.haidong556.chat_server.common.proto.networkPackageProto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: package.proto

// Protobuf Java Version: 3.25.3
public final class PackageProto {
  private PackageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Package)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <pre>
     * 字符串字段
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <pre>
     * 字符串字段
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <pre>
     * 整数字段
     * </pre>
     *
     * <code>int32 messageNum = 3;</code>
     * @return The messageNum.
     */
    int getMessageNum();

    /**
     * <pre>
     * 重复的字符串字段
     * </pre>
     *
     * <code>repeated .Message message = 4;</code>
     */
    java.util.List<PackageProto.Message>
        getMessageList();
    /**
     * <pre>
     * 重复的字符串字段
     * </pre>
     *
     * <code>repeated .Message message = 4;</code>
     */
    PackageProto.Message getMessage(int index);
    /**
     * <pre>
     * 重复的字符串字段
     * </pre>
     *
     * <code>repeated .Message message = 4;</code>
     */
    int getMessageCount();
    /**
     * <pre>
     * 重复的字符串字段
     * </pre>
     *
     * <code>repeated .Message message = 4;</code>
     */
    java.util.List<? extends PackageProto.MessageOrBuilder>
        getMessageOrBuilderList();
    /**
     * <pre>
     * 重复的字符串字段
     * </pre>
     *
     * <code>repeated .Message message = 4;</code>
     */
    PackageProto.MessageOrBuilder getMessageOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Package}
   */
  public static final class Package extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Package)
      PackageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Package.newBuilder() to construct.
    private Package(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Package() {
      type_ = "";
      message_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Package();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PackageProto.internal_static_Package_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PackageProto.internal_static_Package_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PackageProto.Package.class, PackageProto.Package.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_ = 0L;
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object type_ = "";
    /**
     * <pre>
     * 字符串字段
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 字符串字段
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGENUM_FIELD_NUMBER = 3;
    private int messageNum_ = 0;
    /**
     * <pre>
     * 整数字段
     * </pre>
     *
     * <code>int32 messageNum = 3;</code>
     * @return The messageNum.
     */
    @java.lang.Override
    public int getMessageNum() {
      return messageNum_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<PackageProto.Message> message_;
    /**
     * <pre>
     * 重复的字符串字段
     * </pre>
     *
     * <code>repeated .Message message = 4;</code>
     */
    @java.lang.Override
    public java.util.List<PackageProto.Message> getMessageList() {
      return message_;
    }
    /**
     * <pre>
     * 重复的字符串字段
     * </pre>
     *
     * <code>repeated .Message message = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends PackageProto.MessageOrBuilder>
        getMessageOrBuilderList() {
      return message_;
    }
    /**
     * <pre>
     * 重复的字符串字段
     * </pre>
     *
     * <code>repeated .Message message = 4;</code>
     */
    @java.lang.Override
    public int getMessageCount() {
      return message_.size();
    }
    /**
     * <pre>
     * 重复的字符串字段
     * </pre>
     *
     * <code>repeated .Message message = 4;</code>
     */
    @java.lang.Override
    public PackageProto.Message getMessage(int index) {
      return message_.get(index);
    }
    /**
     * <pre>
     * 重复的字符串字段
     * </pre>
     *
     * <code>repeated .Message message = 4;</code>
     */
    @java.lang.Override
    public PackageProto.MessageOrBuilder getMessageOrBuilder(
        int index) {
      return message_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeInt64(1, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      if (messageNum_ != 0) {
        output.writeInt32(3, messageNum_);
      }
      for (int i = 0; i < message_.size(); i++) {
        output.writeMessage(4, message_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      if (messageNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, messageNum_);
      }
      for (int i = 0; i < message_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, message_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PackageProto.Package)) {
        return super.equals(obj);
      }
      PackageProto.Package other = (PackageProto.Package) obj;

      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getType()
          .equals(other.getType())) return false;
      if (getMessageNum()
          != other.getMessageNum()) return false;
      if (!getMessageList()
          .equals(other.getMessageList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + MESSAGENUM_FIELD_NUMBER;
      hash = (53 * hash) + getMessageNum();
      if (getMessageCount() > 0) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessageList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PackageProto.Package parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PackageProto.Package parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PackageProto.Package parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PackageProto.Package parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PackageProto.Package parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PackageProto.Package parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PackageProto.Package parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PackageProto.Package parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PackageProto.Package parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static PackageProto.Package parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PackageProto.Package parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PackageProto.Package parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PackageProto.Package prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Package}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Package)
        PackageProto.PackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PackageProto.internal_static_Package_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PackageProto.internal_static_Package_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PackageProto.Package.class, PackageProto.Package.Builder.class);
      }

      // Construct using PackageOuterClass.Package.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestamp_ = 0L;
        type_ = "";
        messageNum_ = 0;
        if (messageBuilder_ == null) {
          message_ = java.util.Collections.emptyList();
        } else {
          message_ = null;
          messageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PackageProto.internal_static_Package_descriptor;
      }

      @java.lang.Override
      public PackageProto.Package getDefaultInstanceForType() {
        return PackageProto.Package.getDefaultInstance();
      }

      @java.lang.Override
      public PackageProto.Package build() {
        PackageProto.Package result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PackageProto.Package buildPartial() {
        PackageProto.Package result = new PackageProto.Package(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(PackageProto.Package result) {
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            message_ = java.util.Collections.unmodifiableList(message_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
      }

      private void buildPartial0(PackageProto.Package result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestamp_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.messageNum_ = messageNum_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PackageProto.Package) {
          return mergeFrom((PackageProto.Package)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PackageProto.Package other) {
        if (other == PackageProto.Package.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getMessageNum() != 0) {
          setMessageNum(other.getMessageNum());
        }
        if (messageBuilder_ == null) {
          if (!other.message_.isEmpty()) {
            if (message_.isEmpty()) {
              message_ = other.message_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureMessageIsMutable();
              message_.addAll(other.message_);
            }
            onChanged();
          }
        } else {
          if (!other.message_.isEmpty()) {
            if (messageBuilder_.isEmpty()) {
              messageBuilder_.dispose();
              messageBuilder_ = null;
              message_ = other.message_;
              bitField0_ = (bitField0_ & ~0x00000008);
              messageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMessageFieldBuilder() : null;
            } else {
              messageBuilder_.addAllMessages(other.message_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                type_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                messageNum_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                PackageProto.Message m =
                    input.readMessage(
                        PackageProto.Message.parser(),
                        extensionRegistry);
                if (messageBuilder_ == null) {
                  ensureMessageIsMutable();
                  message_.add(m);
                } else {
                  messageBuilder_.addMessage(m);
                }
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long timestamp_ ;
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <pre>
       * 字符串字段
       * </pre>
       *
       * <code>string type = 2;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 字符串字段
       * </pre>
       *
       * <code>string type = 2;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 字符串字段
       * </pre>
       *
       * <code>string type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        type_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 字符串字段
       * </pre>
       *
       * <code>string type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = getDefaultInstance().getType();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 字符串字段
       * </pre>
       *
       * <code>string type = 2;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        type_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int messageNum_ ;
      /**
       * <pre>
       * 整数字段
       * </pre>
       *
       * <code>int32 messageNum = 3;</code>
       * @return The messageNum.
       */
      @java.lang.Override
      public int getMessageNum() {
        return messageNum_;
      }
      /**
       * <pre>
       * 整数字段
       * </pre>
       *
       * <code>int32 messageNum = 3;</code>
       * @param value The messageNum to set.
       * @return This builder for chaining.
       */
      public Builder setMessageNum(int value) {

        messageNum_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 整数字段
       * </pre>
       *
       * <code>int32 messageNum = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        messageNum_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<PackageProto.Message> message_ =
        java.util.Collections.emptyList();
      private void ensureMessageIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          message_ = new java.util.ArrayList<PackageProto.Message>(message_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PackageProto.Message, PackageProto.Message.Builder, PackageProto.MessageOrBuilder> messageBuilder_;

      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public java.util.List<PackageProto.Message> getMessageList() {
        if (messageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(message_);
        } else {
          return messageBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public int getMessageCount() {
        if (messageBuilder_ == null) {
          return message_.size();
        } else {
          return messageBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public PackageProto.Message getMessage(int index) {
        if (messageBuilder_ == null) {
          return message_.get(index);
        } else {
          return messageBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public Builder setMessage(
          int index, PackageProto.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.set(index, value);
          onChanged();
        } else {
          messageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public Builder setMessage(
          int index, PackageProto.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.set(index, builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public Builder addMessage(PackageProto.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.add(value);
          onChanged();
        } else {
          messageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public Builder addMessage(
          int index, PackageProto.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.add(index, value);
          onChanged();
        } else {
          messageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public Builder addMessage(
          PackageProto.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.add(builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public Builder addMessage(
          int index, PackageProto.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.add(index, builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public Builder addAllMessage(
          java.lang.Iterable<? extends PackageProto.Message> values) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, message_);
          onChanged();
        } else {
          messageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          messageBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public Builder removeMessage(int index) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.remove(index);
          onChanged();
        } else {
          messageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public PackageProto.Message.Builder getMessageBuilder(
          int index) {
        return getMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public PackageProto.MessageOrBuilder getMessageOrBuilder(
          int index) {
        if (messageBuilder_ == null) {
          return message_.get(index);  } else {
          return messageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public java.util.List<? extends PackageProto.MessageOrBuilder>
           getMessageOrBuilderList() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(message_);
        }
      }
      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public PackageProto.Message.Builder addMessageBuilder() {
        return getMessageFieldBuilder().addBuilder(
            PackageProto.Message.getDefaultInstance());
      }
      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public PackageProto.Message.Builder addMessageBuilder(
          int index) {
        return getMessageFieldBuilder().addBuilder(
            index, PackageProto.Message.getDefaultInstance());
      }
      /**
       * <pre>
       * 重复的字符串字段
       * </pre>
       *
       * <code>repeated .Message message = 4;</code>
       */
      public java.util.List<PackageProto.Message.Builder>
           getMessageBuilderList() {
        return getMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PackageProto.Message, PackageProto.Message.Builder, PackageProto.MessageOrBuilder>
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PackageProto.Message, PackageProto.Message.Builder, PackageProto.MessageOrBuilder>(
                  message_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Package)
    }

    // @@protoc_insertion_point(class_scope:Package)
    private static final PackageProto.Package DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PackageProto.Package();
    }

    public static PackageProto.Package getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Package>
        PARSER = new com.google.protobuf.AbstractParser<Package>() {
      @java.lang.Override
      public Package parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Package> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Package> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PackageProto.Package getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 messageId = 1;</code>
     * @return The messageId.
     */
    long getMessageId();

    /**
     * <code>int64 messageConversationId = 2;</code>
     * @return The messageConversationId.
     */
    long getMessageConversationId();

    /**
     * <code>int64 messageCreateTime = 3;</code>
     * @return The messageCreateTime.
     */
    long getMessageCreateTime();

    /**
     * <code>int64 messageSenderId = 4;</code>
     * @return The messageSenderId.
     */
    long getMessageSenderId();

    /**
     * <code>int64 messageReceiverId = 5;</code>
     * @return The messageReceiverId.
     */
    long getMessageReceiverId();

    /**
     * <code>string messageContext = 6;</code>
     * @return The messageContext.
     */
    java.lang.String getMessageContext();
    /**
     * <code>string messageContext = 6;</code>
     * @return The bytes for messageContext.
     */
    com.google.protobuf.ByteString
        getMessageContextBytes();

    /**
     * <code>bool messageRead = 7;</code>
     * @return The messageRead.
     */
    boolean getMessageRead();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      messageContext_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PackageProto.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PackageProto.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PackageProto.Message.class, PackageProto.Message.Builder.class);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private long messageId_ = 0L;
    /**
     * <code>int64 messageId = 1;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public long getMessageId() {
      return messageId_;
    }

    public static final int MESSAGECONVERSATIONID_FIELD_NUMBER = 2;
    private long messageConversationId_ = 0L;
    /**
     * <code>int64 messageConversationId = 2;</code>
     * @return The messageConversationId.
     */
    @java.lang.Override
    public long getMessageConversationId() {
      return messageConversationId_;
    }

    public static final int MESSAGECREATETIME_FIELD_NUMBER = 3;
    private long messageCreateTime_ = 0L;
    /**
     * <code>int64 messageCreateTime = 3;</code>
     * @return The messageCreateTime.
     */
    @java.lang.Override
    public long getMessageCreateTime() {
      return messageCreateTime_;
    }

    public static final int MESSAGESENDERID_FIELD_NUMBER = 4;
    private long messageSenderId_ = 0L;
    /**
     * <code>int64 messageSenderId = 4;</code>
     * @return The messageSenderId.
     */
    @java.lang.Override
    public long getMessageSenderId() {
      return messageSenderId_;
    }

    public static final int MESSAGERECEIVERID_FIELD_NUMBER = 5;
    private long messageReceiverId_ = 0L;
    /**
     * <code>int64 messageReceiverId = 5;</code>
     * @return The messageReceiverId.
     */
    @java.lang.Override
    public long getMessageReceiverId() {
      return messageReceiverId_;
    }

    public static final int MESSAGECONTEXT_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object messageContext_ = "";
    /**
     * <code>string messageContext = 6;</code>
     * @return The messageContext.
     */
    @java.lang.Override
    public java.lang.String getMessageContext() {
      java.lang.Object ref = messageContext_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageContext_ = s;
        return s;
      }
    }
    /**
     * <code>string messageContext = 6;</code>
     * @return The bytes for messageContext.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageContextBytes() {
      java.lang.Object ref = messageContext_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageContext_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGEREAD_FIELD_NUMBER = 7;
    private boolean messageRead_ = false;
    /**
     * <code>bool messageRead = 7;</code>
     * @return The messageRead.
     */
    @java.lang.Override
    public boolean getMessageRead() {
      return messageRead_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0L) {
        output.writeInt64(1, messageId_);
      }
      if (messageConversationId_ != 0L) {
        output.writeInt64(2, messageConversationId_);
      }
      if (messageCreateTime_ != 0L) {
        output.writeInt64(3, messageCreateTime_);
      }
      if (messageSenderId_ != 0L) {
        output.writeInt64(4, messageSenderId_);
      }
      if (messageReceiverId_ != 0L) {
        output.writeInt64(5, messageReceiverId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageContext_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, messageContext_);
      }
      if (messageRead_ != false) {
        output.writeBool(7, messageRead_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, messageId_);
      }
      if (messageConversationId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, messageConversationId_);
      }
      if (messageCreateTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, messageCreateTime_);
      }
      if (messageSenderId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, messageSenderId_);
      }
      if (messageReceiverId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, messageReceiverId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageContext_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, messageContext_);
      }
      if (messageRead_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, messageRead_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PackageProto.Message)) {
        return super.equals(obj);
      }
      PackageProto.Message other = (PackageProto.Message) obj;

      if (getMessageId()
          != other.getMessageId()) return false;
      if (getMessageConversationId()
          != other.getMessageConversationId()) return false;
      if (getMessageCreateTime()
          != other.getMessageCreateTime()) return false;
      if (getMessageSenderId()
          != other.getMessageSenderId()) return false;
      if (getMessageReceiverId()
          != other.getMessageReceiverId()) return false;
      if (!getMessageContext()
          .equals(other.getMessageContext())) return false;
      if (getMessageRead()
          != other.getMessageRead()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageId());
      hash = (37 * hash) + MESSAGECONVERSATIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageConversationId());
      hash = (37 * hash) + MESSAGECREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageCreateTime());
      hash = (37 * hash) + MESSAGESENDERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageSenderId());
      hash = (37 * hash) + MESSAGERECEIVERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageReceiverId());
      hash = (37 * hash) + MESSAGECONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getMessageContext().hashCode();
      hash = (37 * hash) + MESSAGEREAD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMessageRead());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PackageProto.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PackageProto.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PackageProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PackageProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PackageProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PackageProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PackageProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PackageProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PackageProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static PackageProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PackageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PackageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PackageProto.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        PackageProto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PackageProto.internal_static_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PackageProto.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PackageProto.Message.class, PackageProto.Message.Builder.class);
      }

      // Construct using PackageOuterClass.Message.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        messageId_ = 0L;
        messageConversationId_ = 0L;
        messageCreateTime_ = 0L;
        messageSenderId_ = 0L;
        messageReceiverId_ = 0L;
        messageContext_ = "";
        messageRead_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PackageProto.internal_static_Message_descriptor;
      }

      @java.lang.Override
      public PackageProto.Message getDefaultInstanceForType() {
        return PackageProto.Message.getDefaultInstance();
      }

      @java.lang.Override
      public PackageProto.Message build() {
        PackageProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PackageProto.Message buildPartial() {
        PackageProto.Message result = new PackageProto.Message(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(PackageProto.Message result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.messageId_ = messageId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.messageConversationId_ = messageConversationId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.messageCreateTime_ = messageCreateTime_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.messageSenderId_ = messageSenderId_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.messageReceiverId_ = messageReceiverId_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.messageContext_ = messageContext_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.messageRead_ = messageRead_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PackageProto.Message) {
          return mergeFrom((PackageProto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PackageProto.Message other) {
        if (other == PackageProto.Message.getDefaultInstance()) return this;
        if (other.getMessageId() != 0L) {
          setMessageId(other.getMessageId());
        }
        if (other.getMessageConversationId() != 0L) {
          setMessageConversationId(other.getMessageConversationId());
        }
        if (other.getMessageCreateTime() != 0L) {
          setMessageCreateTime(other.getMessageCreateTime());
        }
        if (other.getMessageSenderId() != 0L) {
          setMessageSenderId(other.getMessageSenderId());
        }
        if (other.getMessageReceiverId() != 0L) {
          setMessageReceiverId(other.getMessageReceiverId());
        }
        if (!other.getMessageContext().isEmpty()) {
          messageContext_ = other.messageContext_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.getMessageRead() != false) {
          setMessageRead(other.getMessageRead());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                messageId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                messageConversationId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                messageCreateTime_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                messageSenderId_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                messageReceiverId_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                messageContext_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 56: {
                messageRead_ = input.readBool();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long messageId_ ;
      /**
       * <code>int64 messageId = 1;</code>
       * @return The messageId.
       */
      @java.lang.Override
      public long getMessageId() {
        return messageId_;
      }
      /**
       * <code>int64 messageId = 1;</code>
       * @param value The messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageId(long value) {

        messageId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 messageId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = 0L;
        onChanged();
        return this;
      }

      private long messageConversationId_ ;
      /**
       * <code>int64 messageConversationId = 2;</code>
       * @return The messageConversationId.
       */
      @java.lang.Override
      public long getMessageConversationId() {
        return messageConversationId_;
      }
      /**
       * <code>int64 messageConversationId = 2;</code>
       * @param value The messageConversationId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageConversationId(long value) {

        messageConversationId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 messageConversationId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageConversationId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageConversationId_ = 0L;
        onChanged();
        return this;
      }

      private long messageCreateTime_ ;
      /**
       * <code>int64 messageCreateTime = 3;</code>
       * @return The messageCreateTime.
       */
      @java.lang.Override
      public long getMessageCreateTime() {
        return messageCreateTime_;
      }
      /**
       * <code>int64 messageCreateTime = 3;</code>
       * @param value The messageCreateTime to set.
       * @return This builder for chaining.
       */
      public Builder setMessageCreateTime(long value) {

        messageCreateTime_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 messageCreateTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        messageCreateTime_ = 0L;
        onChanged();
        return this;
      }

      private long messageSenderId_ ;
      /**
       * <code>int64 messageSenderId = 4;</code>
       * @return The messageSenderId.
       */
      @java.lang.Override
      public long getMessageSenderId() {
        return messageSenderId_;
      }
      /**
       * <code>int64 messageSenderId = 4;</code>
       * @param value The messageSenderId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageSenderId(long value) {

        messageSenderId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 messageSenderId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageSenderId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        messageSenderId_ = 0L;
        onChanged();
        return this;
      }

      private long messageReceiverId_ ;
      /**
       * <code>int64 messageReceiverId = 5;</code>
       * @return The messageReceiverId.
       */
      @java.lang.Override
      public long getMessageReceiverId() {
        return messageReceiverId_;
      }
      /**
       * <code>int64 messageReceiverId = 5;</code>
       * @param value The messageReceiverId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageReceiverId(long value) {

        messageReceiverId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int64 messageReceiverId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageReceiverId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        messageReceiverId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object messageContext_ = "";
      /**
       * <code>string messageContext = 6;</code>
       * @return The messageContext.
       */
      public java.lang.String getMessageContext() {
        java.lang.Object ref = messageContext_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageContext_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messageContext = 6;</code>
       * @return The bytes for messageContext.
       */
      public com.google.protobuf.ByteString
          getMessageContextBytes() {
        java.lang.Object ref = messageContext_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageContext_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageContext = 6;</code>
       * @param value The messageContext to set.
       * @return This builder for chaining.
       */
      public Builder setMessageContext(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        messageContext_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string messageContext = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageContext() {
        messageContext_ = getDefaultInstance().getMessageContext();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string messageContext = 6;</code>
       * @param value The bytes for messageContext to set.
       * @return This builder for chaining.
       */
      public Builder setMessageContextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        messageContext_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private boolean messageRead_ ;
      /**
       * <code>bool messageRead = 7;</code>
       * @return The messageRead.
       */
      @java.lang.Override
      public boolean getMessageRead() {
        return messageRead_;
      }
      /**
       * <code>bool messageRead = 7;</code>
       * @param value The messageRead to set.
       * @return This builder for chaining.
       */
      public Builder setMessageRead(boolean value) {

        messageRead_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>bool messageRead = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageRead() {
        bitField0_ = (bitField0_ & ~0x00000040);
        messageRead_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final PackageProto.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PackageProto.Message();
    }

    public static PackageProto.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PackageProto.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Package_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Package_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpackage.proto\"Y\n\007Package\022\021\n\ttimestamp\030" +
      "\001 \001(\003\022\014\n\004type\030\002 \001(\t\022\022\n\nmessageNum\030\003 \001(\005\022" +
      "\031\n\007message\030\004 \003(\0132\010.Message\"\267\001\n\007Message\022\021" +
      "\n\tmessageId\030\001 \001(\003\022\035\n\025messageConversation" +
      "Id\030\002 \001(\003\022\031\n\021messageCreateTime\030\003 \001(\003\022\027\n\017m" +
      "essageSenderId\030\004 \001(\003\022\031\n\021messageReceiverI" +
      "d\030\005 \001(\003\022\026\n\016messageContext\030\006 \001(\t\022\023\n\013messa" +
      "geRead\030\007 \001(\010b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Package_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Package_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Package_descriptor,
        new java.lang.String[] { "Timestamp", "Type", "MessageNum", "Message", });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "MessageId", "MessageConversationId", "MessageCreateTime", "MessageSenderId", "MessageReceiverId", "MessageContext", "MessageRead", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
