server:
  port: 9001
  servlet:
    context-path: /oauth
spring:
#  config:
#    import: nacos:oauth-server.properties
#    import: nacos:key-config.properties

  cloud:
    nacos:
      config:
        server-addr: http://localhost:8848
        import-check:
          enabled: false
      discovery:
        server-addr: http://localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/oauth
    username: oauth
    password: 000227
    driver-class-name: com.mysql.cj.jdbc.Driver
#  data:
#    redis:
#      database: 0
#      port: 6379
#      password:
#      host: 127.0.0.1
  application:
    name: oauth-server

  level:
    org:
      springframework: INFO
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
